In [1]:
import pandas as pd
from glob import glob

In [2]:
HVI_files = sorted(glob('datasets/LBhvi_*.csv'))
HVI_files

['datasets/LBhvi_1bedroom.csv',
 'datasets/LBhvi_2bedroom.csv',
 'datasets/LBhvi_3bedroom.csv',
 'datasets/LBhvi_4bedroom.csv',
 'datasets/LBhvi_5BedroomOrMore.csv']

In [3]:
Sqft_files = sorted(glob('datasets/LB_MedianRentalPricePerSqft_*.csv'))
Sqft_files

['datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv',
 'datasets/LB_MedianRentalPricePerSqft_2Bedroom.csv',
 'datasets/LB_MedianRentalPricePerSqft_3Bedroom.csv',
 'datasets/LB_MedianRentalPricePerSqft_4Bedroom.csv',
 'datasets/LB_MedianRentalPricePerSqft_5BedroomOrMore.csv']

In [4]:
Rent_Unit_files = sorted(glob('datasets/LB_MedianRentalPrice_*.csv'))
Rent_Unit_files

['datasets/LB_MedianRentalPrice_1Bedroom.csv',
 'datasets/LB_MedianRentalPrice_2Bedroom.csv',
 'datasets/LB_MedianRentalPrice_3Bedroom.csv',
 'datasets/LB_MedianRentalPrice_4Bedroom.csv',
 'datasets/LB_MedianRentalPrice_5BedroomOrMore.csv']

In [5]:
HVI_data = pd.concat((pd.read_csv(file, encoding = "ISO-8859-1").assign(filename = file)
          for file in HVI_files), ignore_index = True, sort = False)

In [6]:
Sqft_data = pd.concat((pd.read_csv(file, encoding = "ISO-8859-1").assign(filename = file)
          for file in Sqft_files), ignore_index = True, sort = False)

In [7]:
Rent_Unit_data = pd.concat((pd.read_csv(file, encoding = "ISO-8859-1").assign(filename = file)
          for file in Rent_Unit_files), ignore_index = True, sort = False)

In [8]:
HVI_data

,RegionID,RegionName,State,Metro,CountyName,SizeRank,2008-01,2008-02,2008-03,2008-04,...,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,filename
0,6181,New York,NY,New York-Newark-Jersey City,Queens County,1,421862.0,422369.5,4.219167e+05,4.219253e+05,...,6.093657e+05,6.077580e+05,6.071727e+05,6.067477e+05,6.062653e+05,6.046240e+05,6.017487e+05,5.996973e+05,5.984163e+05,datasets/LBhvi_1bedroom.csv
1,12447,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,2,NaN,NaN,NaN,NaN,...,5.040593e+05,5.041367e+05,5.047590e+05,5.068017e+05,5.097507e+05,5.133227e+05,5.179030e+05,5.206980e+05,5.228407e+05,datasets/LBhvi_1bedroom.csv
2,39051,Houston,TX,Houston-The Woodlands-Sugar Land,Harris County,3,75638.0,75406.5,7.532500e+04,7.507033e+04,...,1.045950e+05,1.045683e+05,1.044997e+05,1.046140e+05,1.046163e+05,1.048913e+05,1.049250e+05,1.055077e+05,1.055867e+05,datasets/LBhvi_1bedroom.csv
3,17426,Chicago,IL,Chicago-Naperville-Elgin,Cook County,4,NaN,NaN,NaN,2.257010e+05,...,2.371833e+05,2.378600e+05,2.382847e+05,2.382007e+05,2.379167e+05,2.375380e+05,2.372133e+05,2.370050e+05,2.369463e+05,datasets/LBhvi_1bedroom.csv
4,6915,San Antonio,TX,San Antonio-New Braunfels,Bexar County,5,67385.0,67579.5,6.770300e+04,6.788233e+04,...,8.820633e+04,8.875700e+04,8.907300e+04,8.974733e+04,9.016833e+04,9.086567e+04,9.195000e+04,9.262633e+04,9.336267e+04,datasets/LBhvi_1bedroom.csv
5,13271,Philadelphia,PA,Philadelphia-Camden-Wilmington,Philadelphia County,6,261422.0,262757.0,2.618743e+05,2.617657e+05,...,2.880320e+05,2.878110e+05,2.879360e+05,2.868350e+05,2.857313e+05,2.846923e+05,2.842710e+05,2.833347e+05,2.823193e+05,datasets/LBhvi_1bedroom.csv
6,40326,Phoenix,AZ,Phoenix-Mesa-Scottsdale,Maricopa County,7,NaN,NaN,NaN,NaN,...,1.604703e+05,1.612797e+05,1.620867e+05,1.628593e+05,1.635713e+05,1.647037e+05,1.654987e+05,1.664533e+05,1.675370e+05,datasets/LBhvi_1bedroom.csv
7,18959,Las Vegas,NV,Las Vegas-Henderson-Paradise,Clark County,8,NaN,NaN,NaN,NaN,...,1.287760e+05,1.296043e+05,1.302437e+05,1.304563e+05,1.299840e+05,1.292457e+05,1.286813e+05,1.287883e+05,1.292453e+05,datasets/LBhvi_1bedroom.csv
8,54296,San Diego,CA,San Diego-Carlsbad,San Diego County,9,251135.0,248644.5,2.471280e+05,2.443307e+05,...,3.328360e+05,3.348003e+05,3.357570e+05,3.369610e+05,3.384057e+05,3.396427e+05,3.394203e+05,3.393640e+05,3.401153e+05,datasets/LBhvi_1bedroom.csv
9,38128,Dallas,TX,Dallas-Fort Worth-Arlington,Dallas County,10,63511.0,62866.0,6.290700e+04,6.273433e+04,...,1.347740e+05,1.346573e+05,1.342697e+05,1.346167e+05,1.357777e+05,1.370793e+05,1.382690e+05,1.387993e+05,1.391670e+05,datasets/LBhvi_1bedroom.csv
10,10221,Austin,TX,Austin-Round Rock,Travis County,11,178360.0,177724.0,1.777887e+05,1.774627e+05,...,2.656687e+05,2.664753e+05,2.668200e+05,2.672287e+05,2.671723e+05,2.674583e+05,2.686560e+05,2.691787e+05,2.701980e+05,datasets/LBhvi_1bedroom.csv
11,33839,San Jose,CA,San Jose-Sunnyvale-Santa Clara,Santa Clara County,12,NaN,NaN,NaN,NaN,...,5.769363e+05,5.752677e+05,5.741693e+05,5.704967e+05,5.654510e+05,5.596010e+05,5.577020e+05,5.541133e+05,5.537220e+05,datasets/LBhvi_1bedroom.csv
12,25290,Jacksonville,FL,Jacksonville,Duval County,13,NaN,NaN,NaN,NaN,...,1.057913e+05,1.063077e+05,1.067473e+05,1.074820e+05,1.078930e+05,1.081440e+05,1.082247e+05,1.087983e+05,1.089210e+05,datasets/LBhvi_1bedroom.csv
13,20330,San Francisco,CA,San Francisco-Oakland-Hayward,San Francisco County,14,NaN,874404.0,8.799040e+05,8.794313e+05,...,9.371820e+05,9.378673e+05,9.420930e+05,9.463170e+05,9.410150e+05,9.332103e+05,9.261740e+05,9.218217e+05,9.170287e+05,datasets/LBhvi_1bedroom.csv
14,24043,Charlotte,NC,Charlotte-Concord-Gastonia,Mecklenburg County,15,155576.0,155446.0,1.558660e+05,1.561660e+05,...,1.768480e+05,1.775627e+05,1.786810e+05,1.793020e+05,1.792140e+05,1.792177e+05,1.795837e+05,1.806180e+05,1.821147e+05,datasets/LBhvi_1bedroom.csv
15,7481,Tucson,AZ,Tucson,Pima County,16,NaN,121466.0,1.213050e+05,1.207493e+05,...,1.293823e+05,1.299007e+05,1.302597e+05,1.317767e+05,1.329283e+05,1.343463e+05,1.353543e+05,1.362907e+05,1.376283e+05,datasets/LBhvi_1bedroom.csv
16,10920,Columbus,OH,Columbus,Franklin County,17,NaN,NaN,NaN,NaN,...,1.007967e+05,1.013183e+05,1.020323e+05,1.023943e+05,1.024930e+05,1.026363e+05,1.035023e+05,1.044470e+05,1.050523e+05,datasets/LBhvi_1bedroom.csv
17,12455,Louisville,KY,Louisville/Jefferson County,Jefferson County,18,85159.0,85464.0,8.572800e+04,8.626433e+04,...,9.930533e+04,9.991567e+04,1.009000e+05,1.020953e+05,1.030553e+05,1.038690e+05,1.047547e+05,1.056960e+05,1.068170e+05,datasets/LBhvi_1bedroom.csv
18,17933,El Paso,TX,El Paso,El Paso County,19,97732.0,97791.5,9.770100e+04,9.748567e+04,...,8.766567e+04,8.855733e+04,8.966667e+04,9.041667e+04,9.137867e+04,9.184767e+04,9.171900e+04,9.129967e+04,9.113333e+04,datasets/LBhvi_1bedroom.csv
19,11093,Denver,CO,Denver-Aurora-Lakewood,Denver County,20,156232.0,155596.0,1.549933e+05,1.534890e+05,...,2.795793e+05,2.785207e+05,2.772270e+05,2.768343e+05,2.773367e+05,2.781510e+05,2.795487e+05,2.799500e+05,2.802293e+05,datasets/LBhvi_1bedroom.csv
20,16037,Seattle,WA,Seattle-Tacoma-Bellevue,King County,21,326806.0,326270.5,3.253603e+05,3.231650e+05,...,4.871733e+05,4.830540e+05,4.777770e+05,4.712007e+05,4.671700e+05,4.651920e+05,4.636447e+05,4.616137e+05,4.622580e+05,datasets/LBhvi_1bedroom.csv
21,32811,Memphis,TN,Memphis,Shelby County,22,75379.0,74763.5,7.474467e+04,7.441900e+04,...,7.614300e+04,7.694067e+04,7.773700e+04,7.863400e+04,7.906233e+04,7.939067e+04,7.980533e+04,7.994533e+04,8.027367e+04,datasets/LBhvi_1bedroom.csv
22,44269,Boston,MA,Boston-Cambridge-Newton,Suffolk County,23,344764.0,340990.5,3.414287e+05,3.402447e+05,...,5.737760e+05,5.749840e+05,5.793543e+05,5.807363e+05,5.787267e+05,5.758537e+05,5.748653e+05,5.748503e+05,5.737167e+05,datasets/LBhvi_1bedroom.csv
23,41568,Washington,DC,Washington-Arlington-Alexandria,District of Columbia,24,346378.0,345547.0,3.445463e+05,3.428013e+05,...,4.090163e+05,4.102457e+05,4.117687e+05,4.120080e+05,4.113200e+05,4.123167e+05,4.138827e+05,4.159893e+05,4.170477e+05,datasets/LBhvi_1bedroom.csv
24,13373,Portland,OR,Portland-Vancouver-Hillsboro,Multnomah County,25,262660.0,263883.0,2.632330e+05,2.614110e+05,...,3.553580e+05,3.545450e+05,3.529550e+05,3.513137e+05,3.491693e+05,3.479833e+05,3.471773e+05,3.481710e+05,3.502550e+05,datasets/LBhvi_1bedroom.csv
25,6118,Nashville,TN,Nashville-Davidson--Murfreesboro--Franklin,Davidson County,26,154834.0,154789.5,1.549937e+05,1.555733e+05,...,2.278370e+05,2.272263e+05,2.269303e+05,2.273300e+05,2.274700e+05,2.276177e+05,2.280630e+05,2.288487e+05,2.299000e+05,datasets/LBhvi_1bedroom.csv
26,20288,Sacramento,CA,Sacramento--Roseville--Arden-Arcade,Sacramento County,27,NaN,NaN,NaN,NaN,...,2.272227e+05,2.295590e+05,2.318630e+05,2.335980e+05,2.351907e+05,2.370367e+05,2.393697e+05,2.408030e+05,2.426483e+05,datasets/LBhvi_1bedroom.csv
27,3523,Baltimore,MD,Baltimore-Columbia-Towson,Baltimore City,28,173627.0,173346.5,1.736153e+05,1.742430e+05,...,1.523233e+05,1.518600e+05,1.511510e+05,1.511007e+05,1.508330e+05,1.505723e+05,1.493270e+05,1.486200e+05,1.478060e+05,datasets/LBhvi_1bedroom.csv
28,5976,Milwaukee,WI,Milwaukee-Waukesha-West Allis,Milwaukee County,29,NaN,NaN,NaN,NaN,...,1.509877e+05,1.520317e+05,1.530377e+05,1.527653e+05,1.527657e+05,1.530043e+05,1.536487e+05,1.544213e+05,1.547813e+05,datasets/LBhvi_1bedroom.csv
29,40152,Omaha,NE,Omaha-Council Bluffs,Douglas County,30,NaN,NaN,NaN,NaN,...,9.685600e+04,9.737433e+04,9.804233e+04,9.827700e+04,9.843133e+04,9.928467e+04,1.002547e+05,1.005740e+05,1.004803e+05,datasets/LBhvi_1bedroom.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91809,48066,Twin Bridges,CA,Sacramento--Roseville--Arden-Arcade,El Dorado County,17540,NaN,NaN,NaN,NaN,...,4.834810e+05,4.860323e+05,4.905293e+05,4.944520e+05,4.986700e+05,4.981077e+05,5.013540e+05,5.071130e+05,5.130543e+05,datasets/LBhvi_5BedroomOrMore.csv
91810,52367,Gypsum,KS,Salina,Saline County,17541,NaN,NaN,NaN,NaN,...,1.015583e+05,1.032207e+05,1.046273e+05,1.062863e+05,1.068697e+05,1.072440e+05,1.067280e+05,1.070910e+05,1.071453e+05,datasets/LBhvi_5BedroomOrMore.csv
91811,41081,Stockton,UT,Salt Lake City,Tooele County,17542,NaN,NaN,NaN,NaN,...,3.626487e+05,3.626860e+05,3.638973e+05,3.663323e+05,3.711083e+05,3.760660e+05,3.806787e+05,3.849163e+05,3.900437e+05,datasets/LBhvi_5BedroomOrMore.csv
91812,18696,Interlaken,NY,Seneca Falls,Seneca County,17543,121213.0,121756.0,1.217120e+05,1.211647e+05,...,1.476193e+05,1.488370e+05,1.499297e+05,1.504873e+05,1.508743e+05,1.510780e+05,1.514893e+05,1.524390e+05,1.537000e+05,datasets/LBhvi_5BedroomOrMore.csv
91813,11394,Fairfield,WA,Spokane-Spokane Valley,Spokane County,17544,212243.0,212875.0,2.129093e+05,2.134383e+05,...,2.296930e+05,2.320277e+05,2.355907e+05,2.382443e+05,2.406523e+05,2.423813e+05,2.437690e+05,2.447493e+05,2.447040e+05,datasets/LBhvi_5BedroomOrMore.csv
91814,44936,Diggins,MO,Springfield,Webster County,17545,NaN,NaN,NaN,NaN,...,1.084007e+05,1.093690e+05,1.102980e+05,1.111500e+05,1.121140e+05,1.124673e+05,1.128443e+05,1.129253e+05,1.130887e+05,datasets/LBhvi_5BedroomOrMore.csv
91815,50335,Saddlebrooke,MO,Springfield,Christian County,17546,598979.0,594052.5,5.916843e+05,5.871913e+05,...,4.715117e+05,4.704573e+05,4.686840e+05,4.673410e+05,4.666777e+05,4.702477e+05,4.740307e+05,4.716137e+05,4.667437e+05,datasets/LBhvi_5BedroomOrMore.csv
91816,24864,Gilman,MN,St. Cloud,Benton County,17547,NaN,NaN,NaN,NaN,...,2.221407e+05,2.255383e+05,2.296907e+05,2.315290e+05,2.335857e+05,2.348903e+05,2.364163e+05,2.378557e+05,2.382893e+05,datasets/LBhvi_5BedroomOrMore.csv
91817,239445,Central,UT,St. George,Washington County,17548,NaN,NaN,2.305620e+05,2.292870e+05,...,3.466113e+05,3.468673e+05,3.477460e+05,3.474573e+05,3.459840e+05,3.432153e+05,3.416013e+05,3.411227e+05,3.425040e+05,datasets/LBhvi_5BedroomOrMore.csv
91818,37075,Albers,IL,St. Louis,Clinton County,17549,NaN,177780.0,1.781555e+05,1.787847e+05,...,2.087393e+05,2.071847e+05,2.060483e+05,2.049673e+05,2.051077e+05,2.050077e+05,2.052060e+05,2.065047e+05,2.062093e+05,datasets/LBhvi_5BedroomOrMore.csv
91819,172353,Country Life Acres,MO,St. Louis,Saint Louis County,17550,1448771.0,1455612.0,1.451717e+06,1.446514e+06,...,1.672080e+06,1.678197e+06,1.675087e+06,1.663231e+06,1.650126e+06,1.639697e+06,1.640911e+06,1.646643e+06,1.646343e+06,datasets/LBhvi_5BedroomOrMore.csv
91820,172966,Glen Echo Park,MO,St. Louis,Saint Louis County,17551,NaN,NaN,NaN,NaN,...,1.119333e+05,1.116993e+05,1.115610e+05,1.120057e+05,1.126640e+05,1.126673e+05,1.116880e+05,1.099557e+05,1.083780e+05,datasets/LBhvi_5BedroomOrMore.csv
91821,50631,Aaronsburg,PA,State College,Centre County,17552,NaN,NaN,NaN,NaN,...,1.748483e+05,1.757020e+05,1.752153e+05,1.754960e+05,1.768887e+05,1.800053e+05,1.821200e+05,1.831563e+05,1.830833e+05,datasets/LBhvi_5BedroomOrMore.csv
91822,6051,Morrisville,NY,Syracuse,Madison County,17553,96617.0,96559.5,9.647667e+04,9.590433e+04,...,1.107817e+05,1.110450e+05,1.106463e+05,1.099537e+05,1.095700e+05,1.093880e+05,1.091773e+05,1.094290e+05,1.101603e+05,datasets/LBhvi_5BedroomOrMore.csv
91823,38271,Earlville,NY,Syracuse,Madison County,17554,83480.0,83292.0,8.326900e+04,8.288133e+04,...,8.748733e+04,8.774267e+04,8.767933e+04,8.772600e+04,8.750767e+04,8.781733e+04,8.766300e+04,8.725500e+04,8.704767e+04,datasets/LBhvi_5BedroomOrMore.csv
91824,22166,Haskins,OH,Toledo,Wood County,17555,227122.0,226530.0,2.262837e+05,2.254053e+05,...,1.917020e+05,1.933210e+05,1.946920e+05,1.964850e+05,1.978903e+05,2.001217e+05,2.013780e+05,2.030087e+05,2.032780e+05,datasets/LBhvi_5BedroomOrMore.csv
91825,52928,Leland,MI,Traverse City,Leelanau County,17556,NaN,NaN,NaN,NaN,...,6.551690e+05,6.584583e+05,6.604747e+05,6.594613e+05,6.561587e+05,6.544227e+05,6.562907e+05,6.586460e+05,6.573743e+05,datasets/LBhvi_5BedroomOrMore.csv
91826,5941,Middleville,NY,Utica-Rome,Herkimer County,17557,83869.0,83736.5,8.372800e+04,8.325667e+04,...,1.071683e+05,1.078390e+05,1.087297e+05,1.101740e+05,1.110663e+05,1.116863e+05,1.124013e+05,1.137093e+05,1.151117e+05,datasets/LBhvi_5BedroomOrMore.csv
91827,33471,Poland,NY,Utica-Rome,Herkimer County,17558,113461.0,112762.5,1.121577e+05,1.105800e+05,...,1.120403e+05,1.119330e+05,1.117637e+05,1.120817e+05,1.120020e+05,1.119327e+05,1.113623e+05,1.107070e+05,1.099183e+05,datasets/LBhvi_5BedroomOrMore.csv
91828,53725,Oneida Castle,NY,Utica-Rome,Oneida County,17559,NaN,NaN,NaN,NaN,...,1.686373e+05,1.677467e+05,1.683987e+05,1.690600e+05,1.695380e+05,1.693643e+05,1.682993e+05,1.668210e+05,1.649893e+05,datasets/LBhvi_5BedroomOrMore.csv
91829,13346,Point Harbor,NC,Virginia Beach-Norfolk-Newport News,Currituck County,17560,NaN,NaN,NaN,NaN,...,6.937263e+05,6.934527e+05,6.949773e+05,6.998640e+05,7.039560e+05,7.068043e+05,7.072833e+05,7.072560e+05,7.048393e+05,datasets/LBhvi_5BedroomOrMore.csv
91830,44942,Dixie,WA,Walla Walla,Walla Walla County,17561,NaN,NaN,NaN,NaN,...,9.833667e+04,9.778233e+04,9.723867e+04,9.700333e+04,9.656667e+04,9.661900e+04,9.724167e+04,9.847533e+04,9.875133e+04,datasets/LBhvi_5BedroomOrMore.csv
91831,6722,Reinbeck,IA,Waterloo-Cedar Falls,Grundy County,17562,167162.0,166298.5,1.660980e+05,1.660100e+05,...,1.906817e+05,1.918643e+05,1.931843e+05,1.940057e+05,1.953883e+05,1.959450e+05,1.965993e+05,1.966613e+05,1.968223e+05,datasets/LBhvi_5BedroomOrMore.csv
91832,15309,Evans Mills,NY,Watertown-Fort Drum,Jefferson County,17563,233366.0,234557.5,2.335667e+05,2.337973e+05,...,2.105373e+05,2.103273e+05,2.077703e+05,2.053850e+05,2.041217e+05,2.025040e+05,2.019503e+05,2.008013e+05,1.997627e+05,datasets/LBhvi_5BedroomOrMore.csv
91833,25735,Mannsville,NY,Watertown-Fort Drum,Jefferson County,17564,128196.0,126880.0,1.265687e+05,1.267407e+05,...,1.315967e+05,1.332917e+05,1.337423e+05,1.333933e+05,1.323067e+05,1.308163e+05,1.300740e+05,1.288970e+05,1.284110e+05,datasets/LBhvi_5BedroomOrMore.csv
91834,48742,Chaumont,NY,Watertown-Fort Drum,Jefferson County,17565,146409.0,145625.5,1.457367e+05,1.456183e+05,...,1.832753e+05,1.828037e+05,1.840873e+05,1.839210e+05,1.843630e+05,1.832690e+05,1.831797e+05,1.823417e+05,1.814310e+05,datasets/LBhvi_5BedroomOrMore.csv
91835,52819,La Fargeville,NY,Watertown-Fort Drum,Jefferson County,17566,110554.0,110937.5,1.118453e+05,1.130577e+05,...,1.240697e+05,1.226927e+05,1.217037e+05,1.214487e+05,1.219283e+05,1.222793e+05,1.225137e+05,1.229733e+05,1.232507e+05,datasets/LBhvi_5BedroomOrMore.csv
91836,40673,Sabina,OH,Wilmington,Clinton County,17567,NaN,NaN,NaN,NaN,...,6.740467e+04,6.763067e+04,6.784767e+04,6.789467e+04,6.795333e+04,6.804200e+04,6.844100e+04,6.903900e+04,7.011533e+04,datasets/LBhvi_5BedroomOrMore.csv
91837,30201,Altura,MN,Winona,Winona County,17568,177373.0,177369.0,1.766673e+05,1.760753e+05,...,1.833950e+05,1.852127e+05,1.849693e+05,1.840983e+05,1.837670e+05,1.848003e+05,1.849317e+05,1.844843e+05,1.841673e+05,datasets/LBhvi_5BedroomOrMore.csv
91838,29120,Lewisberry,PA,York-Hanover,York County,17569,NaN,NaN,NaN,NaN,...,1.461963e+05,1.459350e+05,1.455350e+05,1.451420e+05,1.453660e+05,1.451967e+05,1.446860e+05,1.437830e+05,1.436623e+05,datasets/LBhvi_5BedroomOrMore.csv

In [9]:
long_beach = ['Long Beach']
LB_hvi = HVI_data.loc[HVI_data['RegionName'].isin(long_beach)]
LB_hvi.head()

,RegionID,RegionName,State,Metro,CountyName,SizeRank,2008-01,2008-02,2008-03,2008-04,...,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,filename
38,46298,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,39,NaN,NaN,252912.0,250754.0,...,332211.00000,333092.00000,333968.33330,335913.66670,336132.0000,337113.33330,338481.33330,340667.00000,342447.6667,datasets/LBhvi_1bedroom.csv
1459,46300,Long Beach,NY,New York-Newark-Jersey City,Nassau County,1460,NaN,NaN,NaN,NaN,...,436995.66670,438161.66670,438718.00000,435997.00000,430988.6667,426213.33330,423995.33330,423796.00000,423608.6667,datasets/LBhvi_1bedroom.csv
2466,39494,Long Beach,MS,Gulfport-Biloxi-Pascagoula,Harrison County,2467,NaN,NaN,NaN,NaN,...,94439.33333,95000.33333,95571.66667,96258.66667,96194.0000,96295.66667,96624.66667,97626.33333,98532.0000,datasets/LBhvi_1bedroom.csv
6817,19083,Long Beach,WA,NaN,Pacific County,6818,122427.0,122648.5,122576.0,122139.0,...,130571.00000,131452.66670,132444.00000,133429.00000,133304.0000,133258.66670,132792.33330,133430.33330,133235.6667,datasets/LBhvi_1bedroom.csv
11149,46298,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,44,NaN,NaN,NaN,NaN,...,475720.33330,476933.33330,478145.00000,479735.66670,481859.3333,485573.00000,491071.00000,495943.00000,499596.6667,datasets/LBhvi_2bedroom.csv

In [10]:
CA_longbeach = ['CA']
LB_hvi = LB_hvi.loc[LB_hvi['State'].isin(CA_longbeach)]
LB_hvi

,RegionID,RegionName,State,Metro,CountyName,SizeRank,2008-01,2008-02,2008-03,2008-04,...,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,filename
38,46298,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,39,NaN,NaN,252912.0000,250754.0000,...,332211.0000,333092.0000,333968.3333,335913.6667,336132.0000,337113.3333,338481.3333,340667.0000,342447.6667,datasets/LBhvi_1bedroom.csv
11149,46298,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,44,NaN,NaN,NaN,NaN,...,475720.3333,476933.3333,478145.0000,479735.6667,481859.3333,485573.0000,491071.0000,495943.0000,499596.6667,datasets/LBhvi_2bedroom.csv
30701,46298,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,44,NaN,NaN,452671.0000,447087.0000,...,646603.3333,647143.0000,648373.0000,650964.0000,649060.0000,648352.0000,649207.3333,653945.3333,657643.3333,datasets/LBhvi_3bedroom.csv
52450,46298,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,44,570465.0,563756.0,557048.6667,543984.3333,...,747016.6667,746953.0000,749199.0000,752364.3333,749998.3333,749282.0000,749735.0000,755699.0000,759652.0000,datasets/LBhvi_4bedroom.csv
74312,46298,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,43,665228.0,659409.0,652628.3333,638500.3333,...,868033.0000,871478.6667,875895.0000,882400.3333,888190.0000,894773.3333,902023.6667,908066.0000,912182.0000,datasets/LBhvi_5BedroomOrMore.csv

In [11]:
for col in LB_hvi.columns:
    if col <= '2018-12':
        del LB_hvi[col]

In [12]:
LB_hvi = LB_hvi.drop(columns=['Metro', 'CountyName'])

LB_hvi

,RegionID,RegionName,State,SizeRank,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,filename
38,46298,Long Beach,CA,39,331678.0000,332009.0000,332211.0000,333092.0000,333968.3333,335913.6667,336132.0000,337113.3333,338481.3333,340667.0000,342447.6667,datasets/LBhvi_1bedroom.csv
11149,46298,Long Beach,CA,44,475870.6667,475687.3333,475720.3333,476933.3333,478145.0000,479735.6667,481859.3333,485573.0000,491071.0000,495943.0000,499596.6667,datasets/LBhvi_2bedroom.csv
30701,46298,Long Beach,CA,44,648051.6667,647179.3333,646603.3333,647143.0000,648373.0000,650964.0000,649060.0000,648352.0000,649207.3333,653945.3333,657643.3333,datasets/LBhvi_3bedroom.csv
52450,46298,Long Beach,CA,44,749516.6667,747830.3333,747016.6667,746953.0000,749199.0000,752364.3333,749998.3333,749282.0000,749735.0000,755699.0000,759652.0000,datasets/LBhvi_4bedroom.csv
74312,46298,Long Beach,CA,43,867028.3333,867317.6667,868033.0000,871478.6667,875895.0000,882400.3333,888190.0000,894773.3333,902023.6667,908066.0000,912182.0000,datasets/LBhvi_5BedroomOrMore.csv

In [13]:
LB_hvi = LB_hvi.rename(columns={"2019-01":"January", "2019-02":"February",
                               "2019-03":"March", "2019-04":"April",
                               "2019-05":"May", "2019-06":"June",
                               "2019-07":"July", "2019-08":"August",
                               "2019-09":"September", "2019-10":"October",
                               "2019-11":"November"})
LB_hvi

,RegionID,RegionName,State,SizeRank,January,February,March,April,May,June,July,August,September,October,November,filename
38,46298,Long Beach,CA,39,331678.0000,332009.0000,332211.0000,333092.0000,333968.3333,335913.6667,336132.0000,337113.3333,338481.3333,340667.0000,342447.6667,datasets/LBhvi_1bedroom.csv
11149,46298,Long Beach,CA,44,475870.6667,475687.3333,475720.3333,476933.3333,478145.0000,479735.6667,481859.3333,485573.0000,491071.0000,495943.0000,499596.6667,datasets/LBhvi_2bedroom.csv
30701,46298,Long Beach,CA,44,648051.6667,647179.3333,646603.3333,647143.0000,648373.0000,650964.0000,649060.0000,648352.0000,649207.3333,653945.3333,657643.3333,datasets/LBhvi_3bedroom.csv
52450,46298,Long Beach,CA,44,749516.6667,747830.3333,747016.6667,746953.0000,749199.0000,752364.3333,749998.3333,749282.0000,749735.0000,755699.0000,759652.0000,datasets/LBhvi_4bedroom.csv
74312,46298,Long Beach,CA,43,867028.3333,867317.6667,868033.0000,871478.6667,875895.0000,882400.3333,888190.0000,894773.3333,902023.6667,908066.0000,912182.0000,datasets/LBhvi_5BedroomOrMore.csv

In [14]:
Sqft_data

,RegionName,State,Metro,CountyName,SizeRank,2010-02,2010-03,2010-04,2010-05,2010-06,...,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,filename
0,New York,NY,New York-Newark-Jersey City,Queens County,1,NaN,NaN,NaN,NaN,NaN,...,3.785714,3.980892,3.900000,4.007752,4.000000,4.000000,3.945746,3.881944,3.823529,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
1,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,2,NaN,NaN,NaN,NaN,NaN,...,3.385027,3.424106,3.376361,3.426431,3.428412,3.467466,3.493529,3.433142,3.424731,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
2,Houston,TX,Houston-The Woodlands-Sugar Land,Harris County,3,NaN,NaN,NaN,NaN,NaN,...,1.654930,1.656334,1.658314,1.674041,1.657210,1.656207,1.653675,1.654412,1.629909,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
3,Chicago,IL,Chicago-Naperville-Elgin,Cook County,4,NaN,1.653402,1.666667,1.634755,1.6675,...,2.493830,2.450000,2.454594,2.462590,2.428571,2.416021,2.407696,2.380115,2.417185,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
4,San Antonio,TX,San Antonio-New Braunfels,Bexar County,5,NaN,NaN,NaN,NaN,NaN,...,1.445687,1.447436,1.458333,1.479349,1.486761,1.472311,1.465517,1.469294,1.455848,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
5,Philadelphia,PA,Philadelphia-Camden-Wilmington,Philadelphia County,6,NaN,NaN,NaN,NaN,NaN,...,2.418856,2.401431,2.352941,2.371948,2.348586,2.333333,2.272135,2.268966,2.270649,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
6,Phoenix,AZ,Phoenix-Mesa-Scottsdale,Maricopa County,7,NaN,NaN,NaN,NaN,NaN,...,1.498605,1.565917,1.612903,1.631707,1.572327,1.570000,1.604659,1.590210,1.623584,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
7,Las Vegas,NV,Las Vegas-Henderson-Paradise,Clark County,8,NaN,NaN,NaN,NaN,NaN,...,1.390000,1.409692,1.415000,1.422475,1.420942,1.433520,1.424000,1.416268,1.414767,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
8,San Diego,CA,San Diego-Carlsbad,San Diego County,9,NaN,NaN,NaN,NaN,NaN,...,2.974333,2.973462,3.007075,3.056452,3.078222,3.081325,3.069321,3.025749,2.992918,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
9,Dallas,TX,Dallas-Fort Worth-Arlington,Dallas County,10,NaN,NaN,NaN,NaN,NaN,...,1.851852,1.852113,1.853297,1.859523,1.834278,1.791929,1.788551,1.796760,1.772871,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
10,Austin,TX,Austin-Round Rock,Travis County,11,NaN,NaN,NaN,NaN,NaN,...,1.823649,1.877510,1.909969,1.917698,1.920000,1.937716,1.902000,1.909477,1.913143,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
11,San Jose,CA,San Jose-Sunnyvale-Santa Clara,Santa Clara County,12,NaN,NaN,NaN,NaN,NaN,...,3.494521,3.529033,3.551100,3.606289,3.716963,3.692572,3.632275,3.585736,3.566384,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
12,Jacksonville,FL,Jacksonville,Duval County,13,NaN,NaN,NaN,NaN,NaN,...,1.498397,1.500615,1.476074,1.451613,1.454545,1.436782,1.425851,1.436724,1.500297,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
13,Indianapolis,IN,Indianapolis-Carmel-Anderson,Marion County,14,NaN,NaN,NaN,NaN,NaN,...,1.274221,1.266667,1.250000,1.219847,1.190828,1.187840,1.168224,1.165556,1.179641,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
14,San Francisco,CA,San Francisco-Oakland-Hayward,San Francisco County,15,NaN,NaN,NaN,NaN,NaN,...,5.252664,5.299164,5.423659,5.484694,5.510022,5.554830,5.559503,5.402161,5.401396,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
15,Charlotte,NC,Charlotte-Concord-Gastonia,Mecklenburg County,16,NaN,NaN,NaN,NaN,NaN,...,1.770833,1.764964,1.754381,1.717913,1.800258,1.788434,1.795266,1.741294,1.768942,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
16,Fort Worth,TX,Dallas-Fort Worth-Arlington,Tarrant County,17,NaN,NaN,NaN,NaN,NaN,...,1.804781,1.813070,1.817521,1.738095,1.732644,1.704068,1.658120,1.650966,1.620773,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
17,Tucson,AZ,Tucson,Pima County,18,NaN,NaN,NaN,NaN,NaN,...,1.192146,1.204506,1.169231,1.153846,1.154152,1.202341,1.207252,1.198462,1.205945,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
18,Columbus,OH,Columbus,Franklin County,19,NaN,NaN,NaN,NaN,NaN,...,1.302782,1.287784,1.320059,1.326733,1.305882,1.354167,1.364307,1.369048,1.378116,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
19,Louisville,KY,Louisville/Jefferson County,Jefferson County,20,NaN,NaN,NaN,NaN,NaN,...,1.147059,1.204427,1.200000,1.194564,1.192602,1.166987,1.171329,1.205357,1.208826,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
20,Orlando,FL,Orlando-Kissimmee-Sanford,Orange County,21,NaN,NaN,NaN,NaN,NaN,...,1.744202,1.738400,1.762731,1.797980,1.754078,1.754601,1.749646,1.766625,1.794923,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
21,El Paso,TX,El Paso,El Paso County,22,NaN,NaN,NaN,NaN,NaN,...,1.078571,1.124079,1.097561,1.116919,1.095914,1.100000,1.064927,1.024202,1.003834,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
22,Denver,CO,Denver-Aurora-Lakewood,Denver County,23,NaN,NaN,NaN,NaN,NaN,...,2.202036,2.273869,2.350193,2.385078,2.349760,2.320286,2.293390,2.316626,2.332881,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
23,Seattle,WA,Seattle-Tacoma-Bellevue,King County,24,NaN,NaN,NaN,NaN,NaN,...,3.180473,3.242678,3.265207,3.252646,3.254950,3.237782,3.214863,3.174157,3.129139,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
24,Memphis,TN,Memphis,Shelby County,25,NaN,NaN,NaN,NaN,NaN,...,1.162281,1.186799,1.225554,1.215641,1.286667,1.213333,1.187583,1.187583,1.187583,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
25,Boston,MA,Boston-Cambridge-Newton,Suffolk County,26,NaN,NaN,NaN,NaN,NaN,...,3.836996,3.833333,3.833333,3.931624,3.937770,3.870968,3.869939,3.857143,3.850028,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
26,Washington,DC,Washington-Arlington-Alexandria,District of Columbia,27,NaN,NaN,NaN,NaN,NaN,...,3.416667,3.410265,3.407672,3.443551,3.469388,3.500000,3.466645,3.483728,3.441203,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
27,Portland,OR,Portland-Vancouver-Hillsboro,Multnomah County,28,NaN,NaN,NaN,NaN,NaN,...,2.441016,2.419720,2.432857,2.472005,2.497373,2.513889,2.511719,2.494394,2.490811,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
28,Nashville,TN,Nashville-Davidson--Murfreesboro--Franklin,Davidson County,29,NaN,NaN,NaN,NaN,NaN,...,2.061429,2.037760,2.019481,1.998751,1.895522,1.883827,1.975672,2.049780,2.073170,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
29,Sacramento,CA,Sacramento--Roseville--Arden-Arcade,Sacramento County,30,NaN,NaN,NaN,NaN,NaN,...,1.946003,1.973524,2.074708,2.104184,2.166667,2.104918,2.031414,2.065041,2.083625,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3250,Anchorage,AK,Anchorage,Anchorage Borough,21,NaN,NaN,NaN,NaN,NaN,...,0.601085,0.638492,0.612371,0.622917,0.638000,0.620994,0.638000,0.655683,0.631711,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3251,Plano,TX,Dallas-Fort Worth-Arlington,Collin County,22,NaN,NaN,NaN,NaN,NaN,...,0.846679,0.820274,0.778715,0.777992,0.800000,0.797079,0.800093,0.825010,0.799893,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3252,Henderson,NV,Las Vegas-Henderson-Paradise,Clark County,23,NaN,NaN,NaN,NaN,NaN,...,0.811266,0.844716,0.849265,0.828339,0.816757,0.831217,0.799543,0.816791,0.821945,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3253,Buffalo,NY,Buffalo-Cheektowaga-Niagara Falls,Erie County,24,NaN,NaN,NaN,NaN,NaN,...,0.396601,0.406250,0.413291,0.398724,0.393538,0.402504,0.404377,0.400000,0.399909,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3254,Lawrenceville,GA,Atlanta-Sandy Springs-Roswell,Gwinnett County,25,NaN,NaN,NaN,NaN,NaN,...,0.686407,0.711845,0.712790,0.667165,0.727941,0.695991,0.695186,0.656456,0.672269,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3255,Irvine,CA,Los Angeles-Long Beach-Anaheim,Orange County,26,NaN,NaN,NaN,NaN,NaN,...,1.641284,1.719148,1.721557,1.764114,1.750381,1.707703,1.675148,1.643074,1.702490,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3256,Chesapeake,VA,Virginia Beach-Norfolk-Newport News,Chesapeake City,27,NaN,NaN,NaN,NaN,NaN,...,0.766122,0.744999,0.745785,0.745054,0.739226,0.745033,0.720199,0.704205,0.721587,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3257,Yonkers,NY,New York-Newark-Jersey City,Westchester County,28,NaN,NaN,NaN,NaN,NaN,...,0.926784,0.848739,0.897010,0.962363,0.980123,0.875698,0.927721,0.972690,1.029853,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3258,Providence,RI,Providence-Warwick,Providence County,29,NaN,NaN,NaN,NaN,NaN,...,0.764656,0.761509,0.671517,0.639318,0.589696,0.562852,0.585480,0.623701,0.721696,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3259,Sugar Land,TX,Houston-The Woodlands-Sugar Land,Fort Bend County,30,NaN,NaN,NaN,NaN,NaN,...,0.776791,0.782417,0.794805,0.796709,0.791059,0.785498,0.762965,0.782123,0.770429,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3260,Cumming,GA,Atlanta-Sandy Springs-Roswell,Forsyth County,31,NaN,NaN,NaN,NaN,NaN,...,0.687718,0.693681,0.691422,0.691667,0.687500,0.738215,0.729102,0.696822,0.710050,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3261,Frisco,TX,Dallas-Fort Worth-Arlington,Collin County,32,NaN,NaN,NaN,NaN,NaN,...,0.808080,0.839825,0.839825,0.820448,0.798334,0.768329,0.771907,0.773036,0.793221,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3262,Bellevue,WA,Seattle-Tacoma-Bellevue,King County,33,NaN,NaN,NaN,NaN,NaN,...,1.140143,1.279412,1.288911,1.280992,1.266962,1.356784,1.255973,1.206960,1.224490,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3263,Bloomington,IN,Bloomington,Monroe County,34,NaN,NaN,NaN,NaN,NaN,...,1.757188,1.712981,1.926667,1.775630,1.806084,2.099328,1.972854,1.802885,1.789848,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3264,New Haven,CT,New Haven-Milford,New Haven County,35,NaN,NaN,NaN,NaN,NaN,...,0.443787,0.436943,0.443325,0.431102,0.468119,0.499804,0.474166,0.499804,0.473538,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3265,Murrieta,CA,Riverside-San Bernardino-Ontario,Riverside County,36,NaN,NaN,NaN,NaN,NaN,...,0.794934,0.827815,0.850630,0.851623,0.865692,0.856730,0.802639,0.845770,0.837802,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3266,Temecula,CA,Riverside-San Bernardino-Ontario,Riverside County,37,NaN,NaN,NaN,NaN,NaN,...,0.895075,0.892248,0.905952,0.907915,0.910796,0.884655,0.887850,0.896594,0.922664,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3267,Tracy,CA,Stockton-Lodi,San Joaquin County,38,NaN,NaN,NaN,NaN,NaN,...,0.951132,0.968175,0.935133,0.949469,0.891660,0.914437,0.942101,0.949030,0.947428,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3268,Waterbury,CT,New Haven-Milford,New Haven County,39,NaN,NaN,NaN,NaN,NaN,...,0.271150,0.303574,0.271150,0.263449,0.266106,0.286893,0.307314,0.310007,0.302853,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3269,Newport Beach,CA,Los Angeles-Long Beach-Anaheim,Orange County,40,NaN,NaN,NaN,NaN,NaN,...,2.942006,3.093895,3.200776,3.516279,3.516279,3.430186,3.327867,3.040936,2.948479,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3270,Somerville,MA,Boston-Cambridge-Newton,Middlesex County,41,NaN,NaN,NaN,NaN,NaN,...,1.276256,1.370807,1.331751,1.256640,1.202003,1.193524,1.110032,0.982486,1.039399,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3271,Greenwich,CT,Bridgeport-Stamford-Norwalk,Fairfield County,42,NaN,NaN,NaN,NaN,NaN,...,2.627809,2.670181,2.601042,2.521987,2.429688,2.391232,2.282200,2.216980,2.273125,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3272,Doral,FL,Miami-Fort Lauderdale-West Palm Beach,Miami-Dade County,43,NaN,NaN,NaN,NaN,NaN,...,1.320187,1.310497,1.276131,1.284934,1.296909,1.327913,1.327913,1.353555,1.352097,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3273,Eastvale,CA,Riverside-San Bernardino-Ontario,Riverside County,44,NaN,NaN,NaN,NaN,NaN,...,0.834079,0.822945,0.818371,0.830671,0.839223,0.842473,0.838480,0.853218,0.821388,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3274,Beverly Hills,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,45,NaN,NaN,NaN,NaN,NaN,...,4.139073,4.266031,4.485809,4.599823,4.666554,4.676713,4.977033,4.632065,4.769874,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3275,Sag Harbor,NY,New York-Newark-Jersey City,Suffolk County,46,NaN,NaN,NaN,NaN,NaN,...,12.500000,12.800917,12.800917,12.777667,12.842466,12.755102,10.476000,9.251979,9.420108,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3276,Bridgehampton,NY,New York-Newark-Jersey City,Suffolk County,47,NaN,NaN,NaN,NaN,NaN,...,14.736477,15.388563,16.088061,16.379323,15.945727,15.133520,14.935136,15.000000,14.625586,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3277,Water Mill,NY,New York-Newark-Jersey City,Suffolk County,48,NaN,NaN,NaN,NaN,NaN,...,15.138816,15.822785,16.424289,16.326354,15.610064,13.929603,12.554421,12.112282,13.924051,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3278,Quogue,NY,New York-Newark-Jersey City,Suffolk County,49,NaN,NaN,NaN,NaN,NaN,...,11.000000,9.548438,10.818938,11.748615,10.053740,9.548438,8.531559,7.906250,8.571429,datasets/LB_MedianRentalPricePerSqft_5BedroomO...
3279,Sagaponack,NY,New York-Newark-Jersey City,Suffolk County,50,NaN,NaN,NaN,NaN,NaN,...,17.647059,19.285714,19.107365,19.464286,19.022226,19.107365,16.000000,16.083916,18.947368,datasets/LB_MedianRentalPricePerSqft_5BedroomO...

In [15]:
LB_sqft = Sqft_data.loc[Sqft_data['RegionName'].isin(long_beach)]
LB_sqft
#file for 5+ bedrooms does not have data for Long Beach

,RegionName,State,Metro,CountyName,SizeRank,2010-02,2010-03,2010-04,2010-05,2010-06,...,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,filename
42,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,43,NaN,NaN,NaN,NaN,NaN,...,2.806415,2.750000,2.750000,2.711075,2.791667,2.772727,2.750337,2.713235,2.725080,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
800,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,43,NaN,NaN,NaN,NaN,NaN,...,2.407240,2.449889,2.441506,2.414325,2.481081,2.443981,2.415966,2.396245,2.401854,datasets/LB_MedianRentalPricePerSqft_2Bedroom.csv
2015,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,44,NaN,NaN,NaN,NaN,NaN,...,2.000000,2.000000,2.081406,2.015825,2.057692,2.071698,2.105263,2.104911,2.146154,datasets/LB_MedianRentalPricePerSqft_3Bedroom.csv
2956,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,39,NaN,NaN,NaN,NaN,NaN,...,1.307652,1.219512,1.378005,1.380104,1.351971,1.525229,1.331884,1.386482,1.523137,datasets/LB_MedianRentalPricePerSqft_4Bedroom.csv

In [16]:
for col in LB_sqft.columns:
    if col <= '2018-12':
        del LB_sqft[col]

In [17]:
LB_sqft = LB_sqft.drop(columns=['Metro', 'CountyName'])
LB_sqft

,RegionName,State,SizeRank,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,filename
42,Long Beach,CA,43,2.701351,2.752830,2.806415,2.750000,2.750000,2.711075,2.791667,2.772727,2.750337,2.713235,2.725080,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
800,Long Beach,CA,43,2.365302,2.382770,2.407240,2.449889,2.441506,2.414325,2.481081,2.443981,2.415966,2.396245,2.401854,datasets/LB_MedianRentalPricePerSqft_2Bedroom.csv
2015,Long Beach,CA,44,1.922254,1.937417,2.000000,2.000000,2.081406,2.015825,2.057692,2.071698,2.105263,2.104911,2.146154,datasets/LB_MedianRentalPricePerSqft_3Bedroom.csv
2956,Long Beach,CA,39,1.178361,1.236979,1.307652,1.219512,1.378005,1.380104,1.351971,1.525229,1.331884,1.386482,1.523137,datasets/LB_MedianRentalPricePerSqft_4Bedroom.csv

In [18]:
LB_sqft = LB_sqft.rename(columns={"2019-01":"January", "2019-02":"February",
                               "2019-03":"March", "2019-04":"April",
                               "2019-05":"May", "2019-06":"June",
                               "2019-07":"July", "2019-08":"August",
                               "2019-09":"September", "2019-10":"October",
                               "2019-11":"November"})
LB_sqft

,RegionName,State,SizeRank,January,February,March,April,May,June,July,August,September,October,November,filename
42,Long Beach,CA,43,2.701351,2.752830,2.806415,2.750000,2.750000,2.711075,2.791667,2.772727,2.750337,2.713235,2.725080,datasets/LB_MedianRentalPricePerSqft_1Bedroom.csv
800,Long Beach,CA,43,2.365302,2.382770,2.407240,2.449889,2.441506,2.414325,2.481081,2.443981,2.415966,2.396245,2.401854,datasets/LB_MedianRentalPricePerSqft_2Bedroom.csv
2015,Long Beach,CA,44,1.922254,1.937417,2.000000,2.000000,2.081406,2.015825,2.057692,2.071698,2.105263,2.104911,2.146154,datasets/LB_MedianRentalPricePerSqft_3Bedroom.csv
2956,Long Beach,CA,39,1.178361,1.236979,1.307652,1.219512,1.378005,1.380104,1.351971,1.525229,1.331884,1.386482,1.523137,datasets/LB_MedianRentalPricePerSqft_4Bedroom.csv

In [19]:
LB_unit = Rent_Unit_data.loc[Rent_Unit_data['RegionName'].isin(long_beach)]
LB_unit

,RegionName,State,Metro,CountyName,SizeRank,2010-02,2010-03,2010-04,2010-05,2010-06,...,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,filename
42,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,43,NaN,NaN,NaN,NaN,NaN,...,1650.0,1650.0,1645.0,1650.0,1695.0,1675.0,1695.0,1695.0,1650.0,datasets/LB_MedianRentalPrice_1Bedroom.csv
699,Long Beach,NY,New York-Newark-Jersey City,Nassau County,700,NaN,NaN,NaN,NaN,NaN,...,1925.0,1950.0,1950.0,1995.0,1975.0,2000.0,1975.0,1975.0,1950.0,datasets/LB_MedianRentalPrice_1Bedroom.csv
845,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,43,NaN,NaN,NaN,NaN,NaN,...,2192.0,2195.0,2195.0,2200.0,2250.0,2200.0,2195.0,2150.0,2125.0,datasets/LB_MedianRentalPrice_2Bedroom.csv
1847,Long Beach,NY,New York-Newark-Jersey City,Nassau County,1045,NaN,NaN,NaN,NaN,NaN,...,2650.0,2625.0,2675.0,2675.0,2737.5,2800.0,2600.0,2600.0,2550.0,datasets/LB_MedianRentalPrice_2Bedroom.csv
2109,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,44,NaN,NaN,NaN,NaN,NaN,...,2695.0,2670.0,2750.0,2750.0,2700.0,2700.0,2722.5,2750.0,2695.0,datasets/LB_MedianRentalPrice_3Bedroom.csv
2955,Long Beach,NY,New York-Newark-Jersey City,Nassau County,890,NaN,NaN,NaN,NaN,NaN,...,3200.0,3200.0,3300.0,3600.0,3300.0,3200.0,3000.0,3000.0,3000.0,datasets/LB_MedianRentalPrice_3Bedroom.csv
3094,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,40,NaN,NaN,NaN,NaN,NaN,...,2437.5,2450.0,2795.0,2695.0,2595.0,2825.0,2600.0,2595.0,2600.0,datasets/LB_MedianRentalPrice_4Bedroom.csv
3390,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,19,NaN,NaN,NaN,NaN,NaN,...,2259.0,2195.0,2197.5,2195.0,2497.5,2500.0,2395.0,2295.0,2350.0,datasets/LB_MedianRentalPrice_5BedroomOrMore.csv

In [20]:
LB_unit = LB_unit.loc[LB_unit['State'].isin(CA_longbeach)]
LB_unit

,RegionName,State,Metro,CountyName,SizeRank,2010-02,2010-03,2010-04,2010-05,2010-06,...,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,filename
42,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,43,NaN,NaN,NaN,NaN,NaN,...,1650.0,1650.0,1645.0,1650.0,1695.0,1675.0,1695.0,1695.0,1650.0,datasets/LB_MedianRentalPrice_1Bedroom.csv
845,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,43,NaN,NaN,NaN,NaN,NaN,...,2192.0,2195.0,2195.0,2200.0,2250.0,2200.0,2195.0,2150.0,2125.0,datasets/LB_MedianRentalPrice_2Bedroom.csv
2109,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,44,NaN,NaN,NaN,NaN,NaN,...,2695.0,2670.0,2750.0,2750.0,2700.0,2700.0,2722.5,2750.0,2695.0,datasets/LB_MedianRentalPrice_3Bedroom.csv
3094,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,40,NaN,NaN,NaN,NaN,NaN,...,2437.5,2450.0,2795.0,2695.0,2595.0,2825.0,2600.0,2595.0,2600.0,datasets/LB_MedianRentalPrice_4Bedroom.csv
3390,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,19,NaN,NaN,NaN,NaN,NaN,...,2259.0,2195.0,2197.5,2195.0,2497.5,2500.0,2395.0,2295.0,2350.0,datasets/LB_MedianRentalPrice_5BedroomOrMore.csv

In [21]:
for col in LB_unit.columns:
    if col <= '2018-12':
        del LB_unit[col]

In [22]:
LB_unit = LB_unit.drop(columns=['Metro', 'CountyName'])
LB_unit

,RegionName,State,SizeRank,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,filename
42,Long Beach,CA,43,1625.0,1675.0,1650.0,1650.0,1645.0,1650.0,1695.0,1675.0,1695.0,1695.0,1650.0,datasets/LB_MedianRentalPrice_1Bedroom.csv
845,Long Beach,CA,43,2100.0,2150.0,2192.0,2195.0,2195.0,2200.0,2250.0,2200.0,2195.0,2150.0,2125.0,datasets/LB_MedianRentalPrice_2Bedroom.csv
2109,Long Beach,CA,44,2599.5,2600.0,2695.0,2670.0,2750.0,2750.0,2700.0,2700.0,2722.5,2750.0,2695.0,datasets/LB_MedianRentalPrice_3Bedroom.csv
3094,Long Beach,CA,40,2400.0,2400.0,2437.5,2450.0,2795.0,2695.0,2595.0,2825.0,2600.0,2595.0,2600.0,datasets/LB_MedianRentalPrice_4Bedroom.csv
3390,Long Beach,CA,19,2300.0,2200.0,2259.0,2195.0,2197.5,2195.0,2497.5,2500.0,2395.0,2295.0,2350.0,datasets/LB_MedianRentalPrice_5BedroomOrMore.csv

In [23]:
LB_unit = LB_unit.rename(columns={"2019-01":"January", "2019-02":"February",
                               "2019-03":"March", "2019-04":"April",
                               "2019-05":"May", "2019-06":"June",
                               "2019-07":"July", "2019-08":"August",
                               "2019-09":"September", "2019-10":"October",
                               "2019-11":"November"})
LB_unit

,RegionName,State,SizeRank,January,February,March,April,May,June,July,August,September,October,November,filename
42,Long Beach,CA,43,1625.0,1675.0,1650.0,1650.0,1645.0,1650.0,1695.0,1675.0,1695.0,1695.0,1650.0,datasets/LB_MedianRentalPrice_1Bedroom.csv
845,Long Beach,CA,43,2100.0,2150.0,2192.0,2195.0,2195.0,2200.0,2250.0,2200.0,2195.0,2150.0,2125.0,datasets/LB_MedianRentalPrice_2Bedroom.csv
2109,Long Beach,CA,44,2599.5,2600.0,2695.0,2670.0,2750.0,2750.0,2700.0,2700.0,2722.5,2750.0,2695.0,datasets/LB_MedianRentalPrice_3Bedroom.csv
3094,Long Beach,CA,40,2400.0,2400.0,2437.5,2450.0,2795.0,2695.0,2595.0,2825.0,2600.0,2595.0,2600.0,datasets/LB_MedianRentalPrice_4Bedroom.csv
3390,Long Beach,CA,19,2300.0,2200.0,2259.0,2195.0,2197.5,2195.0,2497.5,2500.0,2395.0,2295.0,2350.0,datasets/LB_MedianRentalPrice_5BedroomOrMore.csv

In [24]:
LB_hvi.to_csv('datasets/LongBeach_HVI.csv',index=False)

In [25]:
LB_sqft.to_csv('datasets/LongBeach_Rent_SqFt.csv', index=False)

In [26]:
LB_unit.to_csv('datasets/LongBeach_Rent_Unit.csv', index=False)